language: ruby
rvm:
- 2.1
- 2.2
- 2.3.3
- 2.4.0
- ruby-head
cache: bundler
bundler_args: --jobs=2
before_script:
- export CODECLIMATE_REPO_TOKEN=586f55fe847c8d296adc6a00e2adf651cd63f4ea3c6ae79e7d723ad2c1f86ffc
- export COVERAGE=true
script:
- bundle exec rspec
- bundle exec codeclimate-test-reporter
branches:
  only:
    - master
notifications:
  email: false
matrix:
  allow_failures:
  - rvm: ruby-head
sudo: false
